### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by walcivar** [scottdurow/NetworkView#16]
Hi Scott

I'm testing this solution and it is great!!!

I would like to know:
1) if the source code of this solution will be available in the future?
2) At the moment do you give support on this solution?
3) Is there any kind of license or it is free at all?
4) It is available for CRM 2013?

Best Regards
Wilmer Alcivar

**Comment by scottdurow** [comment]
Source code available now.
It is free but no version for CRM2013 due to lack of hierarchical relationships.
