### ISSUE TITLE
Xrm.Sdk.Entity not found

### ISSUE THREAD

**Issue by cseymr** [scottdurow/NetworkView#18]
Issue reported by a developer on my team:  

When I tried to open a Network View, a window opens up and doesn’t show anything but if I check the Developer Tools it says Cannot read property Entity of undefined.  See attachment.

![nv_error1](https://cloud.githubusercontent.com/assets/14763830/24142614/f91b27c2-0e1e-11e7-8996-ba3206aeb538.jpg)

They're using v7.3 of Sparkle and v1.0.4 of NetworkView.
![nv_error2](https://cloud.githubusercontent.com/assets/14763830/24142613/f907220e-0e1e-11e7-80a9-e6eeaedcea49.jpg)

**Comment by scottdurow** [comment]
They will need 1.2 of network view - https://github.com/scottdurow/NetworkView/releases/tag/v1.2.0

**Comment by cseymr** [comment]
Thanks - I think they got 1.0.4 straight off the master branch - might be worth some signposting to the latest version?

![nv_error3](https://cloud.githubusercontent.com/assets/14763830/24143120/8f04094c-0e20-11e7-90c5-da567060199c.jpg)

**Comment by scottdurow** [comment]
Ooh - that shouldn't really have been there - I've deleted it! Thanks for pointing that out.
